language: python
# command to install dependencies
before_script:
  - chmod +x deploy.sh
# command to run tests
script: bash deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "ae5506b755e0"
  - RSTBLOG_REPO: "https://github.com/hermetico/rstblog.git"