language: python
# command to install dependencies
before_install:
  - chmod +x _scripts/install.sh
install:
  - bash ./_scripts/install.sh
before_script:
  - chmod +x _scripts/deploy.sh
# command to run tests
script:
  - bash ./_scripts/deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "03aee79ae867"
  - RSTBLOG_REPO: "https://github.com/hermetico/rstblog.git"
branches:
  only:
    - devel

