active_modules: [pygments, tags, blog, latex, disqus]
author: Juan Marin
canonical_url: http://hermetico.no-ip.org
modules:
  pygments:
    style: tango
  disqus:
    shortname: hermetico
    developer: 1
  blog:
    pub_date_match: /blog/<int:year>/<int:month>/<int:day>/
